<a href="https://colab.research.google.com/github/prof-eduardo-nunes/unicamp-mineracao_dados/blob/main/rede_neural_tabela_verdade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:

import numpy as np


entradas = np.array([[0,0,0],
                     [1,0,0],
                     [0,1,0],
                     [1,1,0],
                     [0,0,1],
                     [1,0,1],
                     [0,1,1],
                     [1,1,1]])

saidas = np.array([[0],[1],[0],[0],[1],[1],[0],[0]])


pesos0 = 2*np.random.random((3,3)) - 1
pesos1 = 2*np.random.random((3,1)) - 1

epocas = 1000
taxaAprendizagem = 10


def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

def sigmoidDerivada(sig):
    return sig * (1 - sig)

def treina_rede(entradas, saidas, pesos0, pesos1, epocas, taxaAprendizagem):
    for j in range(epocas):
        camadaEntrada = entradas
        somaSinapse0 = np.dot(camadaEntrada, pesos0)
        camadaOculta = sigmoid(somaSinapse0)

        somaSinapse1 = np.dot(camadaOculta, pesos1)
        camadaSaida = sigmoid(somaSinapse1)

        erroCamadaSaida = saidas - camadaSaida
        mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))

        derivadaSaida = sigmoidDerivada(camadaSaida)
        deltaSaida = erroCamadaSaida * derivadaSaida

        pesos1Transposta = pesos1.T
        deltaSaidaXPeso = deltaSaida.dot(pesos1Transposta)
        deltaCamadaOculta = deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

        camadaOcultaTransposta = camadaOculta.T
        pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)
        pesos1 = (pesos1) + (pesosNovo1 * taxaAprendizagem)

        camadaEntradaTransposta = camadaEntrada.T
        pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)
        pesos0 = (pesos0) + (pesosNovo0 * taxaAprendizagem)


    print("pesos0:")
    print(pesos0)

    print("pesos1:")
    print(pesos1)

    print("saida esperada:")
    print(saidas)

    print("camada saida calculada:")
    print(camadaSaida)

    print("Erro: " + str(mediaAbsoluta))

    return 0



treina_rede(entradas, saidas, pesos0, pesos1, epocas, taxaAprendizagem)

pesos0:
[[ 2.4199367  -2.67320531 -2.7228382 ]
 [-5.50117648 -1.57104029  6.5289077 ]
 [ 2.47074686 -2.38676974 -2.80108603]]
pesos1:
[[  6.20097726]
 [ -4.31664843]
 [-10.55365564]]
saida esperada:
[[0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]
camada saida calculada:
[[1.29435969e-02]
 [9.91547304e-01]
 [1.29444588e-05]
 [4.05827882e-05]
 [9.91417396e-01]
 [9.97728493e-01]
 [4.10689580e-05]
 [3.87871081e-03]]
Erro: 0.004527963879789513


0