<a href="https://colab.research.google.com/github/prof-eduardo-nunes/unicamp-mineracao_dados/blob/main/rede_neural_tabela_verdade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  # Importa a biblioteca NumPy, usada para operações com arrays e matrizes.

# Dados de entrada da rede neural (8 exemplos com 3 atributos cada).
entradas = np.array([[0,0,0],
                     [1,0,0],
                     [0,1,0],
                     [1,1,0],
                     [0,0,1],
                     [1,0,1],
                     [0,1,1],
                     [1,1,1]])

# Saídas esperadas para cada entrada (valores alvo).
saidas = np.array([[0],[1],[0],[0],[1],[1],[0],[0]])

# Inicializa os pesos da primeira camada (entrada -> oculta) com valores aleatórios entre -1 e 1.
pesos0 = 2 * np.random.random((3, 3)) - 1  # 3 entradas, 3 neurônios na camada oculta
# Inicializa os pesos da segunda camada (oculta -> saída) com valores aleatórios entre -1 e 1.
pesos1 = 2 * np.random.random((3, 1)) - 1  # 3 neurônios ocultos, 1 neurônio de saída

epocas = 1000            # Número de iterações para o treinamento
taxaAprendizagem = 10    # Fator que controla a atualização dos pesos (ajuste alto nesse caso)

# Função de ativação sigmoide
def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

# Derivada da função sigmoide, usada para calcular o gradiente
def sigmoidDerivada(sig):
    return sig * (1 - sig)

# Função principal para treinar a rede
def treina_rede(entradas, saidas, pesos0, pesos1, epocas, taxaAprendizagem):
    for j in range(epocas):
        # Forward pass: calcula a saída da rede
        camadaEntrada = entradas
        somaSinapse0 = np.dot(camadaEntrada, pesos0)     # Produto da entrada com os pesos da 1ª camada
        camadaOculta = sigmoid(somaSinapse0)              # Aplica a função de ativação (camada oculta)

        somaSinapse1 = np.dot(camadaOculta, pesos1)       # Produto da camada oculta com os pesos da 2ª camada
        camadaSaida = sigmoid(somaSinapse1)               # Saída final da rede

        # Backpropagation: ajusta os pesos com base no erro
        erroCamadaSaida = saidas - camadaSaida            # Calcula o erro da saída
        mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))  # Erro médio absoluto para fins de exibição

        derivadaSaida = sigmoidDerivada(camadaSaida)
        deltaSaida = erroCamadaSaida * derivadaSaida      # Gradiente da camada de saída

        # Calcula o delta da camada oculta
        pesos1Transposta = pesos1.T
        deltaSaidaXPeso = deltaSaida.dot(pesos1Transposta)
        deltaCamadaOculta = deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

        # Atualiza os pesos entre a camada oculta e a saída
        camadaOcultaTransposta = camadaOculta.T
        pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)
        pesos1 = pesos1 + (pesosNovo1 * taxaAprendizagem)

        # Atualiza os pesos entre a entrada e a camada oculta
        camadaEntradaTransposta = camadaEntrada.T
        pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)
        pesos0 = pesos0 + (pesosNovo0 * taxaAprendizagem)

    # Exibe os resultados após o treinamento
    print("pesos0:")
    print(pesos0)

    print("pesos1:")
    print(pesos1)

    print("saida esperada:")
    print(saidas)

    print("camada saida calculada:")
    print(camadaSaida)

    print("Erro: " + str(mediaAbsoluta))

    return 0

# Executa o treinamento da rede neural
treina_rede(entradas, saidas, pesos0, pesos1, epocas, taxaAprendizagem)

pesos0:
[[ 2.4199367  -2.67320531 -2.7228382 ]
 [-5.50117648 -1.57104029  6.5289077 ]
 [ 2.47074686 -2.38676974 -2.80108603]]
pesos1:
[[  6.20097726]
 [ -4.31664843]
 [-10.55365564]]
saida esperada:
[[0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]
camada saida calculada:
[[1.29435969e-02]
 [9.91547304e-01]
 [1.29444588e-05]
 [4.05827882e-05]
 [9.91417396e-01]
 [9.97728493e-01]
 [4.10689580e-05]
 [3.87871081e-03]]
Erro: 0.004527963879789513


0